### ISSUE TITLE
Unified Inventory glitch

### ISSUE THREAD

**Issue by aerozoic** [BrunoMine/xpro#2]
Using unified inventory on my server. If i craft an item or dig a node that triggers XP +1 then the player inventory switches to the default inventory and i can't see the unified inventory unless i restart the game.

:large_orange_diamond:

**Comment by BrunoMine** [comment]
Check if `xpro_inventory = unified_inventory` setting is okay in minetest.conf

**Comment by aerozoic** [comment]
I did not see any instructions for that. thanks
:large_orange_diamond:

**Comment by BrunoMine** [comment]
This has happened before. XD 
I just set up an auto detector to avoid this.
